In [1]:
import torch
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt

print(torch.__version__)


2.0.0+cu118


## Introduction to Tensors

### Creating tensors

PyTorch tensors are created using `torch.Tensor()` = https://pytorch.org/docs/stable/tensors.html

In [2]:
# Scalar
scalar = torch.tensor(7)
scalar


tensor(7)

In [3]:
scalar.ndim


0

In [4]:
# Get the Python number within a tensor (only works with one-element tensors)
scalar.item()


7

In [5]:
# Vector
vector = torch.tensor([7, 7])
vector


tensor([7, 7])

In [6]:
vector.ndim


1

In [7]:
vector.shape


torch.Size([2])

In [8]:
# MATRIX
MATRIX = torch.tensor([[7, 8], [9, 10]])
MATRIX


tensor([[ 7,  8],
        [ 9, 10]])

In [9]:
MATRIX.ndim


2

In [10]:
MATRIX[1]


tensor([ 9, 10])

In [11]:
MATRIX.shape


torch.Size([2, 2])

In [12]:
# TENSOR
TENSOR = torch.tensor([[[1, 2, 3], [3, 6, 9], [2, 4, 5]]])
TENSOR


tensor([[[1, 2, 3],
         [3, 6, 9],
         [2, 4, 5]]])

In [13]:
TENSOR.ndim


3

In [14]:
TENSOR.shape


torch.Size([1, 3, 3])

### Random Tensors

Why random tensors?

Random tensors are important because the way neural networks learn is that they start with tensors full of random numbers and then adjust those random numbers to better represent the data.

`Start with random numbers -> look at data -> update random numbers -> look at data -> update random numbers`

Torch random tensors - https://pytorch.org/docs/stable/generated/torch.rand.html 

In [15]:
# Create a random tensor of size (3, 4)
random_tensor = torch.rand(size=(3, 4))
random_tensor


tensor([[0.0130, 0.5820, 0.1220, 0.3984],
        [0.1848, 0.0410, 0.3128, 0.0552],
        [0.2839, 0.1043, 0.4728, 0.2406]])

In [16]:
# Create a random tensor with similar shape to an image tensor
random_image_size_tensor = torch.rand(
    size=(224, 224, 3)
)  # height, width, colour channels (R, G, B)
random_image_size_tensor.shape, random_image_size_tensor.ndim


(torch.Size([224, 224, 3]), 3)

### Zeros and ones

In [17]:
# Create a tensor of all zeros
zeros = torch.zeros(size=(3, 4))
zeros


tensor([[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]])

In [18]:
# Create a tensor of all ones
ones = torch.ones(size=(3, 4))
ones


tensor([[1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.]])

In [19]:
ones.dtype


torch.float32

### Create a range of tensors and tensors-like

In [20]:
# Use torch.range() and get deperecated message, use torch.arange()
one_to_ten = torch.arange(start=1, end=11, step=1)
one_to_ten


tensor([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [21]:
# Creating tensors like
ten_zeros = torch.zeros_like(input=one_to_ten)
ten_zeros


tensor([0, 0, 0, 0, 0, 0, 0, 0, 0, 0])

### Tensor datatypes

**Note:** Tensor datatypes is one of the 3 big errors you'll run into with PyTorch & deep learning:
1. Tensors not right datatype
2. Tensors not right shape
3. Tensors not on the right device

In [22]:
# Float 32 tensor
float_32_tensor = torch.tensor(
    [3.0, 6.0, 9.0],
    dtype=None,  # what data type is the tensor (e.g. float32 or float16)
    device=None,  # what device is your tensor on
    requires_grad=False,  # whether or not to track gradients with this tensor's operations
)
float_32_tensor


tensor([3., 6., 9.])

In [23]:
float_32_tensor.dtype


torch.float32

In [24]:
float_16_tensor = float_32_tensor.type(torch.float16)
float_16_tensor


tensor([3., 6., 9.], dtype=torch.float16)

In [25]:
float_16_tensor * float_32_tensor


tensor([ 9., 36., 81.])

In [26]:
int_32_tensor = torch.tensor([3, 6, 9], dtype=torch.long)
int_32_tensor


tensor([3, 6, 9])

In [27]:
float_32_tensor * int_32_tensor


tensor([ 9., 36., 81.])

### Getting information from tensors

1. Tensors not right datatype - to get datatype from a tensor, can use `tensor.dtype`
2. Tensors not right shape - to get shape from a tensor, can use `tensor.shape`
3. Tensors not on the right device - to get device from a tensor, can use `tensor.device`

In [28]:
# Create a tensor
some_tensor = torch.rand(3, 4)
some_tensor


tensor([[0.8269, 0.8295, 0.0637, 0.1194],
        [0.0076, 0.6129, 0.7381, 0.7090],
        [0.8849, 0.8357, 0.9471, 0.9509]])

In [29]:
# Find out details about some tensor
print(some_tensor)
print(f"Datatype of tensor: {some_tensor.dtype}")
print(f"Shape of tensor: {some_tensor.shape}")
print(f"Device tensor is stored on: {some_tensor.device}")  # will default to CPU


tensor([[0.8269, 0.8295, 0.0637, 0.1194],
        [0.0076, 0.6129, 0.7381, 0.7090],
        [0.8849, 0.8357, 0.9471, 0.9509]])
Datatype of tensor: torch.float32
Shape of tensor: torch.Size([3, 4])
Device tensor is stored on: cpu


### Manipulating tensors (tensor operations)

Tensor operations include:
* Addition
* Subtraction
* Multiplication (element-wise)
* Division
* Matrix multiplication

In [30]:
# Create a tensor and add 10 to it
tensor = torch.tensor([1, 2, 3])
tensor + 10


tensor([11, 12, 13])

In [31]:
# Multiply tensor by 10
tensor * 10


tensor([10, 20, 30])

In [32]:
# Subtract 10
tensor - 10


tensor([-9, -8, -7])

In [33]:
# Try out PyTorch in-built functions
torch.mul(tensor, 10)


tensor([10, 20, 30])

In [34]:
torch.add(tensor, 10)


tensor([11, 12, 13])

### Matrix multiplcation

Two main ways of performing multiplication in neural networks and deep learning:

1. Element-wise multiplication
2. Matrix multiplication (dot product)

In [35]:
# Element-wise multiplication
print(tensor, "*", tensor)
print(f"Equals: {tensor * tensor}")


tensor([1, 2, 3]) * tensor([1, 2, 3])
Equals: tensor([1, 4, 9])


In [36]:
# Matrix multiplication
torch.matmul(tensor, tensor)


tensor(14)

In [37]:
# Matrix multiplication by hand
1 * 1 + 2 * 2 + 3 * 3


14

In [38]:
%%time
value = 0
for i in range(len(tensor)):
    value += tensor[i] * tensor[i]
print(value)


tensor(14)
CPU times: total: 0 ns
Wall time: 2 ms


In [39]:
%%time
torch.matmul(tensor, tensor)


CPU times: total: 0 ns
Wall time: 982 µs


tensor(14)