In [1]:
import torch
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt

print(torch.__version__)


2.0.0+cu118


## Introduction to Tensors

### Creating tensors

PyTorch tensors are created using `torch.Tensor()` = https://pytorch.org/docs/stable/tensors.html

In [2]:
# Scalar
scalar = torch.tensor(7)
scalar


tensor(7)

In [3]:
scalar.ndim


0

In [4]:
# Get the Python number within a tensor (only works with one-element tensors)
scalar.item()


7

In [5]:
# Vector
vector = torch.tensor([7, 7])
vector


tensor([7, 7])

In [6]:
vector.ndim


1

In [7]:
vector.shape


torch.Size([2])

In [8]:
# MATRIX
MATRIX = torch.tensor([[7, 8], [9, 10]])
MATRIX


tensor([[ 7,  8],
        [ 9, 10]])

In [9]:
MATRIX.ndim


2

In [10]:
MATRIX[1]


tensor([ 9, 10])

In [11]:
MATRIX.shape


torch.Size([2, 2])

In [12]:
# TENSOR
TENSOR = torch.tensor([[[1, 2, 3], [3, 6, 9], [2, 4, 5]]])
TENSOR


tensor([[[1, 2, 3],
         [3, 6, 9],
         [2, 4, 5]]])

In [13]:
TENSOR.ndim


3

In [14]:
TENSOR.shape


torch.Size([1, 3, 3])

### Random Tensors

Why random tensors?

Random tensors are important because the way neural networks learn is that they start with tensors full of random numbers and then adjust those random numbers to better represent the data.

`Start with random numbers -> look at data -> update random numbers -> look at data -> update random numbers`

Torch random tensors - https://pytorch.org/docs/stable/generated/torch.rand.html 

In [15]:
# Create a random tensor of size (3, 4)
random_tensor = torch.rand(size=(3, 4))
random_tensor


tensor([[0.7897, 0.4723, 0.5412, 0.7484],
        [0.3688, 0.7119, 0.4060, 0.4260],
        [0.5143, 0.1655, 0.1284, 0.0468]])

In [16]:
# Create a random tensor with similar shape to an image tensor
random_image_size_tensor = torch.rand(
    size=(224, 224, 3)
)  # height, width, colour channels (R, G, B)
random_image_size_tensor.shape, random_image_size_tensor.ndim


(torch.Size([224, 224, 3]), 3)

### Zeros and ones

In [17]:
# Create a tensor of all zeros
zeros = torch.zeros(size=(3, 4))
zeros


tensor([[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]])

In [18]:
# Create a tensor of all ones
ones = torch.ones(size=(3, 4))
ones


tensor([[1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.]])

In [19]:
ones.dtype


torch.float32

### Create a range of tensors and tensors-like

In [20]:
# Use torch.range() and get deperecated message, use torch.arange()
one_to_ten = torch.arange(start=1, end=11, step=1)
one_to_ten


tensor([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [21]:
# Creating tensors like
ten_zeros = torch.zeros_like(input=one_to_ten)
ten_zeros


tensor([0, 0, 0, 0, 0, 0, 0, 0, 0, 0])

### Tensor datatypes

**Note:** Tensor datatypes is one of the 3 big errors you'll run into with PyTorch & deep learning:
1. Tensors not right datatype
2. Tensors not right shape
3. Tensors not on the right device

In [22]:
# Float 32 tensor
float_32_tensor = torch.tensor(
    [3.0, 6.0, 9.0],
    dtype=None,  # what data type is the tensor (e.g. float32 or float16)
    device=None,  # what device is your tensor on
    requires_grad=False,  # whether or not to track gradients with this tensor's operations
)
float_32_tensor


tensor([3., 6., 9.])

In [23]:
float_32_tensor.dtype


torch.float32

In [24]:
float_16_tensor = float_32_tensor.type(torch.float16)
float_16_tensor


tensor([3., 6., 9.], dtype=torch.float16)

In [25]:
float_16_tensor * float_32_tensor


tensor([ 9., 36., 81.])

In [26]:
int_32_tensor = torch.tensor([3, 6, 9], dtype=torch.long)
int_32_tensor


tensor([3, 6, 9])

In [27]:
float_32_tensor * int_32_tensor


tensor([ 9., 36., 81.])

### Getting information from tensors

1. Tensors not right datatype - to get datatype from a tensor, can use `tensor.dtype`
2. Tensors not right shape - to get shape from a tensor, can use `tensor.shape`
3. Tensors not on the right device - to get device from a tensor, can use `tensor.device`

In [28]:
# Create a tensor
some_tensor = torch.rand(3, 4)
some_tensor


tensor([[0.0292, 0.1392, 0.0702, 0.6896],
        [0.0156, 0.5117, 0.6603, 0.7144],
        [0.7901, 0.7541, 0.1891, 0.1135]])

In [29]:
# Find out details about some tensor
print(some_tensor)
print(f"Datatype of tensor: {some_tensor.dtype}")
print(f"Shape of tensor: {some_tensor.shape}")
print(f"Device tensor is stored on: {some_tensor.device}")  # will default to CPU


tensor([[0.0292, 0.1392, 0.0702, 0.6896],
        [0.0156, 0.5117, 0.6603, 0.7144],
        [0.7901, 0.7541, 0.1891, 0.1135]])
Datatype of tensor: torch.float32
Shape of tensor: torch.Size([3, 4])
Device tensor is stored on: cpu


### Manipulating tensors (tensor operations)

Tensor operations include:
* Addition
* Subtraction
* Multiplication (element-wise)
* Division
* Matrix multiplication

In [30]:
# Create a tensor and add 10 to it
tensor = torch.tensor([1, 2, 3])
tensor + 10


tensor([11, 12, 13])

In [31]:
# Multiply tensor by 10
tensor * 10


tensor([10, 20, 30])

In [32]:
# Subtract 10
tensor - 10


tensor([-9, -8, -7])

In [33]:
# Try out PyTorch in-built functions
torch.mul(tensor, 10)


tensor([10, 20, 30])

In [34]:
torch.add(tensor, 10)


tensor([11, 12, 13])

### Matrix multiplcation

Two main ways of performing multiplication in neural networks and deep learning:

1. Element-wise multiplication
2. Matrix multiplication (dot product)

There are two main rules that performing matrix multiplication needs to satisfy:
1. The **inner dimensions** must match:
* `(3, 2) @ (3, 2)` won't work
* `(2, 3) @ (3, 2)` will work
* `(3, 2) @ (2, 3)` will work

2. The resulting matrix has the shape of the **outer dimensions**:
* `(2, 3) @ (3, 2)` -> `(2, 2)`
* `(3, 2) @ (2, 3)` -> `(3, 3)`

In [35]:
# Element-wise multiplication
print(tensor, "*", tensor)
print(f"Equals: {tensor * tensor}")


tensor([1, 2, 3]) * tensor([1, 2, 3])
Equals: tensor([1, 4, 9])


In [36]:
# Matrix multiplication
torch.matmul(tensor, tensor)


tensor(14)

In [37]:
# Matrix multiplication by hand
1 * 1 + 2 * 2 + 3 * 3


14

In [38]:
tensor @ tensor


tensor(14)

In [39]:
%%time
value = 0
for i in range(len(tensor)):
    value += tensor[i] * tensor[i]
print(value)


tensor(14)
CPU times: total: 0 ns
Wall time: 1 ms


In [40]:
%%time
torch.matmul(tensor, tensor)


CPU times: total: 0 ns
Wall time: 0 ns


tensor(14)

### One of the most common errors in deep learning: shape errors

In [41]:
# Shapes for matrix multiplication
tensor_A = torch.tensor([[1, 2], [3, 4], [5, 6]])
tensor_B = torch.tensor([[7, 10], [8, 11], [9, 12]])


In [42]:
# torch.matmul(tensor_A, tensor_B)


In [43]:
tensor_A.shape, tensor_B.shape


(torch.Size([3, 2]), torch.Size([3, 2]))

To fix our tensor shape issues, we can manipulate the shape of one of our tensors using a **transpose**.
A **transpose** switches the axes or dimensions of a given tensor.

In [44]:
tensor_B, tensor_B.shape


(tensor([[ 7, 10],
         [ 8, 11],
         [ 9, 12]]),
 torch.Size([3, 2]))

In [45]:
tensor_B.T, tensor_B.T.shape


(tensor([[ 7,  8,  9],
         [10, 11, 12]]),
 torch.Size([2, 3]))

In [46]:
# The matrix multiplication operation works when tensor_B is tranposed
print(f"Original shapes: tensor_A = {tensor_A.shape}, tensor_B = {tensor_B.shape}")
print(
    f"New shapes: tensor_A = {tensor_A.shape} (same shape as above), tensor_B.T = {tensor_B.T.shape}"
)
print(f"Multiplying: {tensor_A.shape} @ {tensor_B.T.shape} <- inner dimensions match")
print("Output:\n")
output = torch.matmul(tensor_A, tensor_B.T)
print(output)
print(f"\nOutput shape: {output.shape}")


Original shapes: tensor_A = torch.Size([3, 2]), tensor_B = torch.Size([3, 2])
New shapes: tensor_A = torch.Size([3, 2]) (same shape as above), tensor_B.T = torch.Size([2, 3])
Multiplying: torch.Size([3, 2]) @ torch.Size([2, 3]) <- inner dimensions match
Output:

tensor([[ 27,  30,  33],
        [ 61,  68,  75],
        [ 95, 106, 117]])

Output shape: torch.Size([3, 3])


## Finding the min, max, mean, sum, etc (tensor aggregation)

In [47]:
# Create a tensor
x = torch.arange(1, 100, 10)
x


tensor([ 1, 11, 21, 31, 41, 51, 61, 71, 81, 91])

In [48]:
# Find the min
torch.min(x), x.min()


(tensor(1), tensor(1))

In [49]:
# Find the max
torch.max(x), x.max()


(tensor(91), tensor(91))

In [50]:
# Find the mean - note: the torch.mean() function requires a tensor of float32 datatype to work
torch.mean(x.type(torch.float32)), x.type(torch.float32).mean()


(tensor(46.), tensor(46.))

In [51]:
# Find the sum
torch.sum(x), x.sum()


(tensor(460), tensor(460))

### Finding the positional min and max


In [52]:
x


tensor([ 1, 11, 21, 31, 41, 51, 61, 71, 81, 91])

In [53]:
# Find the position in tensor that has hte minimum value with argmin() -> returns index position of target tensor where the minimum value ocxcurs
x.argmin()


tensor(0)

In [54]:
x[0]


tensor(1)

In [55]:
# Find the position in tensor that has hte maximum value with argmax()
x.argmax()


tensor(9)

In [56]:
x[9]


tensor(91)

## Reshaping, stacking, squeezing and unsqueezing tensors

* Reshaping - Reshapes an input tensor to a defined shape
* View - Return a view of an input tensor of certain shape but keep the same memory as the original tensor
* Stacking - Combine multiple tensors on top of each other (vstack) or side by sode (hstack)
* Squeeaze - Remove all `1` dimensions from a tensor
* Unsqueeze - Add a `1` dimension to a target tensor
* Permute - Return a view of the input with dimensions permuted (swapped) in a certain way

In [57]:
# let's create a tensor
x = torch.arange(1.0, 10.0)
x, x.shape


(tensor([1., 2., 3., 4., 5., 6., 7., 8., 9.]), torch.Size([9]))

In [58]:
# Add an extra dimension
x_reshaped = x.reshape(1, 9)
x_reshaped, x_reshaped.shape


(tensor([[1., 2., 3., 4., 5., 6., 7., 8., 9.]]), torch.Size([1, 9]))

In [59]:
# Change the view
z = x.view(1, 9)
z, z.shape


(tensor([[1., 2., 3., 4., 5., 6., 7., 8., 9.]]), torch.Size([1, 9]))

In [60]:
# Changing z changes x (because a view of a tensor shares the same memory as the original input
z[:, 0] = 5
z, x


(tensor([[5., 2., 3., 4., 5., 6., 7., 8., 9.]]),
 tensor([5., 2., 3., 4., 5., 6., 7., 8., 9.]))

In [61]:
# Stack tensors on top of each other
x_stacked = torch.stack([x, x, x, x], dim=0)
x_stacked


tensor([[5., 2., 3., 4., 5., 6., 7., 8., 9.],
        [5., 2., 3., 4., 5., 6., 7., 8., 9.],
        [5., 2., 3., 4., 5., 6., 7., 8., 9.],
        [5., 2., 3., 4., 5., 6., 7., 8., 9.]])