In [1]:
import torch
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt

print(torch.__version__)


2.0.0+cu118


## Introduction to Tensors

### Creating tensors

PyTorch tensors are created using `torch.Tensor()` = https://pytorch.org/docs/stable/tensors.html

In [2]:
# Scalar
scalar = torch.tensor(7)
scalar


tensor(7)

In [3]:
scalar.ndim


0

In [4]:
# Get the Python number within a tensor (only works with one-element tensors)
scalar.item()


7

In [5]:
# Vector
vector = torch.tensor([7, 7])
vector


tensor([7, 7])

In [6]:
vector.ndim


1

In [7]:
vector.shape


torch.Size([2])

In [8]:
# MATRIX
MATRIX = torch.tensor([[7, 8], [9, 10]])
MATRIX


tensor([[ 7,  8],
        [ 9, 10]])

In [9]:
MATRIX.ndim


2

In [10]:
MATRIX[1]


tensor([ 9, 10])

In [11]:
MATRIX.shape


torch.Size([2, 2])

In [12]:
# TENSOR
TENSOR = torch.tensor([[[1, 2, 3], [3, 6, 9], [2, 4, 5]]])
TENSOR


tensor([[[1, 2, 3],
         [3, 6, 9],
         [2, 4, 5]]])

In [13]:
TENSOR.ndim


3

In [14]:
TENSOR.shape


torch.Size([1, 3, 3])