In [1]:
import torch
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt

print(torch.__version__)


2.0.0+cu118


## Introduction to Tensors

### Creating tensors

PyTorch tensors are created using `torch.Tensor()` = https://pytorch.org/docs/stable/tensors.html

In [2]:
# Scalar
scalar = torch.tensor(7)
scalar


tensor(7)

In [3]:
scalar.ndim


0

In [4]:
# Get the Python number within a tensor (only works with one-element tensors)
scalar.item()


7

In [5]:
# Vector
vector = torch.tensor([7, 7])
vector


tensor([7, 7])

In [6]:
vector.ndim


1

In [7]:
vector.shape


torch.Size([2])

In [8]:
# MATRIX
MATRIX = torch.tensor([[7, 8], [9, 10]])
MATRIX


tensor([[ 7,  8],
        [ 9, 10]])

In [9]:
MATRIX.ndim


2

In [10]:
MATRIX[1]


tensor([ 9, 10])

In [11]:
MATRIX.shape


torch.Size([2, 2])

In [12]:
# TENSOR
TENSOR = torch.tensor([[[1, 2, 3], [3, 6, 9], [2, 4, 5]]])
TENSOR


tensor([[[1, 2, 3],
         [3, 6, 9],
         [2, 4, 5]]])

In [13]:
TENSOR.ndim


3

In [14]:
TENSOR.shape


torch.Size([1, 3, 3])

### Random Tensors

Why random tensors?

Random tensors are important because the way neural networks learn is that they start with tensors full of random numbers and then adjust those random numbers to better represent the data.

`Start with random numbers -> look at data -> update random numbers -> look at data -> update random numbers`

Torch random tensors - https://pytorch.org/docs/stable/generated/torch.rand.html 

In [15]:
# Create a random tensor of size (3, 4)
random_tensor = torch.rand(size=(3, 4))
random_tensor


tensor([[0.9429, 0.0772, 0.4180, 0.9798],
        [0.4240, 0.0067, 0.3025, 0.3329],
        [0.8381, 0.2920, 0.7941, 0.6806]])

In [16]:
# Create a random tensor with similar shape to an image tensor
random_image_size_tensor = torch.rand(
    size=(224, 224, 3)
)  # height, width, colour channels (R, G, B)
random_image_size_tensor.shape, random_image_size_tensor.ndim


(torch.Size([224, 224, 3]), 3)

### Zeros and ones

In [17]:
# Create a tensor of all zeros
zeros = torch.zeros(size=(3, 4))
zeros


tensor([[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]])

In [18]:
# Create a tensor of all ones
ones = torch.ones(size=(3, 4))
ones


tensor([[1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.]])

In [19]:
ones.dtype


torch.float32